# Generated by Django 3.0.3 on 2020-05-09 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_titles',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='role',
            field=models.CharField(default='Tech Job', max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
