# Generated by Django 3.0.3 on 2020-05-10 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200509_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('Data Engineer', 'DATA ENGINEER'), ('Software Developer', 'SOFTWARE DEVELOPER'), ('Frontend developer', 'FRONTEND DEVELOPER'), ('Mobile App Developer', 'MOBILE APP DEVELOPER'), ('Technical analyst', 'TECHNINICAL ANALYST'), ('Product Manager', 'PRODUCT MANGER'), ('Project Manager', 'PROJECT MANAGER'), ('Data Scientist', 'DATA SCIENTIST'), ('Data Analyst', 'DATA ANALYST'), ('Database Admin', 'DATABASE ADMIN'), ('Quality Assurance Anlayst', 'QUALITY ASSUARANCE ANALYST'), ('DevOps Engineer', 'DEVOPS ENGINEER'), ('IT Manager', 'IT MANAGER'), ('IT Director', 'IT DIRECTOR')], max_length=50)),
                ('posted_by', models.CharField(max_length=100)),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
